import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import { Providers } from "./providers";

import "./globals.css";
import { Toaster } from "sonner";
import { AppProvider } from "@/context/app-context";
import { ConfirmationDialogProvider } from "@/context/dialog-context";

const nunitoSans = Nunito_Sans({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AppProvider>
        <ConfirmationDialogProvider>
          <body className={`${nunitoSans.variable} antialiased`}>
            <Providers>{children}</Providers>
            <Toaster richColors position="top-right" />
          </body>
        </ConfirmationDialogProvider>
      </AppProvider>
    </html>
  );
}
