openapi: 3.0.3
info:
  title: Go First App API
  description: API documentation for Go First App
  version: 1.2.0

servers:
  - url: http://localhost:8080

# ==================== PATHS ====================
paths:
  /api/login:
    post:
      tags: [Auth]
      summary: Login user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginRequest"
      responses:
        "200":
          description: Login success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/UserResponse"
                      token:
                        type: string
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /api/current:
    get:
      tags: [Auth]
      summary: Get current authenticated user
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successfully retrieved current user
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/UserResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /api/users:
    get:
      tags: [User]
      summary: Get all users
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/PageParam"
        - $ref: "#/components/parameters/PerPageParam"
        - $ref: "#/components/parameters/NameFilterParam"
        - name: username
          in: query
          schema:
            type: string
        - name: phone
          in: query
          schema:
            type: string
        - name: role
          in: query
          schema:
            $ref: "#/components/schemas/UserRole"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/UserResponse"
                      paging:
                        $ref: "#/components/schemas/Paging"
        "401":
          $ref: "#/components/responses/Unauthorized"

    post:
      tags: [User]
      summary: Create a new user
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateUserRequest"
      responses:
        "201":
          description: User created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/UserResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"

  /api/users/{userId}:
    put:
      tags: [User]
      summary: Update user
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/UserIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateUserRequest"
      responses:
        "200":
          description: User updated
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/UserResponse"
        "400":
          $ref: "#/components/responses/BadRequest"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

    delete:
      tags: [User]
      summary: Delete user
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/UserIdParam"
      responses:
        "200":
          $ref: "#/components/responses/DeleteSuccess"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "404":
          $ref: "#/components/responses/NotFound"

  /api/employees:
    get:
      tags: [Employee]
      summary: Get all employees
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/PageParam"
        - $ref: "#/components/parameters/PerPageParam"
        - $ref: "#/components/parameters/NameFilterParam"
        - name: role
          in: query
          schema:
            $ref: "#/components/schemas/EmployeeRole"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      data:
                        type: array
                        items:
                          $ref: "#/components/schemas/EmployeeResponse"
                      paging:
                        $ref: "#/components/schemas/Paging"

    post:
      tags: [Employee]
      summary: Create employee
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateEmployeeRequest"
      responses:
        "201":
          description: Employee created
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/EmployeeResponse"

  /api/employees/{employeeId}:
    get:
      tags: [Employee]
      summary: Get employee by ID
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/EmployeeIdParam"
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/EmployeeResponse"

    put:
      tags: [Employee]
      summary: Update employee
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/EmployeeIdParam"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateEmployeeRequest"
      responses:
        "200":
          description: Employee updated
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/SuccessResponse"
                  - type: object
                    properties:
                      data:
                        $ref: "#/components/schemas/EmployeeResponse"

    delete:
      tags: [Employee]
      summary: Delete employee
      security:
        - BearerAuth: []
      parameters:
        - $ref: "#/components/parameters/EmployeeIdParam"
      responses:
        "200":
          $ref: "#/components/responses/DeleteSuccess"

# ==================== COMPONENTS ====================
components:
  securitySchemes:
    BearerAuth:
      type: apiKey
      in: header
      name: Authorization
      description: "Format: Bearer {token}"

  # ==================== PARAMETERS (Reusable) ====================
  parameters:
    PageParam:
      name: page
      in: query
      description: Page number
      schema:
        type: integer
        default: 1
        minimum: 1

    PerPageParam:
      name: perPage
      in: query
      description: Items per page
      schema:
        type: integer
        default: 10
        minimum: 1
        maximum: 100

    NameFilterParam:
      name: name
      in: query
      description: Filter by name (partial match)
      schema:
        type: string

    UserIdParam:
      name: userId
      in: path
      required: true
      schema:
        type: string
        format: uuid

    EmployeeIdParam:
      name: employeeId
      in: path
      required: true
      schema:
        type: integer

  # ==================== RESPONSES (Reusable) ====================
  responses:
    BadRequest:
      description: Bad request / Validation error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    NotFound:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

    DeleteSuccess:
      description: Successfully deleted
      content:
        application/json:
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: true

  # ==================== SCHEMAS ====================
  schemas:
    # Base Schemas
    SuccessResponse:
      type: object
      properties:
        success:
          type: boolean
          example: true

    Paging:
      type: object
      properties:
        page:
          type: integer
        perPage:
          type: integer
        totalItems:
          type: integer
        totalPages:
          type: integer

    ErrorResponse:
      type: object
      properties:
        code:
          type: integer
        message:
          type: string
        details:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string

    # Common Properties
    PhoneNumber:
      type: string
      pattern: "^08[0-9]{9,11}$"
      example: "08123456789"

    UserRole:
      type: string
      enum: [SUPER_ADMIN, OWNER, WAREHOUSE_HEAD, TREASURER]

    EmployeeRole:
      type: string
      enum: [WAREHOUSE_HEAD, TREASURER, SALES, DRIVER, HELPER, STAFF]

    # Auth
    LoginRequest:
      type: object
      required: [username, password]
      properties:
        username:
          type: string
          minLength: 3
          example: superadmin
        password:
          type: string
          minLength: 6
          example: "123456"

    # User Schemas
    BaseUserFields:
      type: object
      properties:
        name:
          type: string
          minLength: 3
        username:
          type: string
          minLength: 3
        phone:
          $ref: "#/components/schemas/PhoneNumber"
        role:
          $ref: "#/components/schemas/UserRole"

    CreateUserRequest:
      allOf:
        - $ref: "#/components/schemas/BaseUserFields"
        - type: object
          required: [name, username, password, role]
          properties:
            password:
              type: string
              minLength: 6

    UpdateUserRequest:
      allOf:
        - $ref: "#/components/schemas/BaseUserFields"
        - type: object
          required: [name, username, role]
          properties:
            password:
              type: string
              minLength: 6
              description: Optional - only if changing password

    UserResponse:
      allOf:
        - $ref: "#/components/schemas/BaseUserFields"
        - type: object
          properties:
            id:
              type: string
              format: uuid
            createdAt:
              type: string
              format: date-time

    # Employee Schemas
    BaseEmployeeFields:
      type: object
      properties:
        name:
          type: string
          minLength: 3
        salary:
          type: number
          minimum: 0
        role:
          $ref: "#/components/schemas/EmployeeRole"

    CreateEmployeeRequest:
      allOf:
        - $ref: "#/components/schemas/BaseEmployeeFields"
        - type: object
          required: [name, role]
          properties:
            phone:
              $ref: "#/components/schemas/PhoneNumber"
            routes:
              type: array
              items:
                type: integer
              minItems: 1

    UpdateEmployeeRequest:
      allOf:
        - $ref: "#/components/schemas/BaseEmployeeFields"
        - type: object
          required: [name, salary, role]
          properties:
            phone:
              $ref: "#/components/schemas/PhoneNumber"
            routes:
              type: array
              items:
                type: integer
              minItems: 1

    EmployeeResponse:
      allOf:
        - $ref: "#/components/schemas/BaseEmployeeFields"
        - type: object
          properties:
            id:
              type: integer
            phone:
              type: string
            routes:
              type: array
              items:
                type: integer
            createdAt:
              type: string
              format: date-time
