POST http://localhost:8080/api/employees
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE3NzE0OTg0ODQyNDcsImlkIjoiN2Y1ZGM3M2UtZTA5Ny00ZThlLWJhN2MtNWVkODI4ZmFiYzc0In0.vjO5-AaKn5NPze9Nc64IEXD9bnwGGBCZ2kZs8k_TIBE

{
  "name": "Test Manual Sales",
  "role":"SALES",
  "salary":20000,
  "phone":"0812131231",
  "routeIds":[1]
}

### UPDATE EMPLOYEE
PUT http://localhost:8080/api/employees/24
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE3Njc2OTEyNDQ1MDgsImlkIjoiN2Y1ZGM3M2UtZTA5Ny00ZThlLWJhN2MtNWVkODI4ZmFiYzc0In0.gLaXRjgbsmfyN2z2OdE0Cre-7zMGVdjdoR0eIL-AtgE

{
  "name": "Test Manual Employee",
  "role":"STAFF",
  "salary":20000
}

### GET EMPLOYEE ID
GET http://localhost:8080/api/attendance?startDate=2026-01-17&endDate=2026-01-23
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE3NzE0OTg0ODQyNDcsImlkIjoiN2Y1ZGM3M2UtZTA5Ny00ZThlLWJhN2MtNWVkODI4ZmFiYzc0In0.vjO5-AaKn5NPze9Nc64IEXD9bnwGGBCZ2kZs8k_TIBE


### GET EMPLOYEE ID
POST http://localhost:8080/api/attendance/batch
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE3NzE0OTg0ODQyNDcsImlkIjoiN2Y1ZGM3M2UtZTA5Ny00ZThlLWJhN2MtNWVkODI4ZmFiYzc0In0.vjO5-AaKn5NPze9Nc64IEXD9bnwGGBCZ2kZs8k_TIBE

{
    "attendances": [
        {
            "action": "update",
            "date": "2026-01-25",
            "employees": [
                {
                    "id": 1,
                    "status": "PRESENT"
                },
                {
                    "id": 2,
                    "status": "PRESENT"
                },
                {
                    "id": 4,
                    "status": "PRESENT"
                },
                {
                    "id": 5,
                    "status": "PRESENT"
                },
                {
                    "id": 6,
                    "status": "PRESENT"
                },
                {
                    "id": 7,
                    "status": "PRESENT"
                },
                {
                    "id": 8,
                    "status": "PRESENT"
                },
                {
                    "id": 9,
                    "status": "PRESENT"
                },
                {
                    "id": 10,
                    "status": "PRESENT"
                }
            ]
        }
    ]
}