### Find Routes with pagination
GET http://localhost:8080/api/routes?page=1&perPage=10
Accept: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE3NzE0OTg0ODQyNDcsImlkIjoiN2Y1ZGM3M2UtZTA5Ny00ZThlLWJhN2MtNWVkODI4ZmFiYzc0In0.vjO5-AaKn5NPze9Nc64IEXD9bnwGGBCZ2kZs8k_TIBE


### Create Route
POST http://localhost:8080/api/routes
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE3NjQ1MTgwODUxOTgsImlkIjoiN2Y1ZGM3M2UtZTA5Ny00ZThlLWJhN2MtNWVkODI4ZmFiYzc0In0.-Kb8MhiC81AdF9BIqj4D8x-NN9JM57d9SVFr9fK0sKQ

{
  "name": "Test Manual rute",
  "description":"Desc manual rute"
}


### Upadate Route
PUT http://localhost:8080/api/routes/1
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcmUiOjE3NjQ1MTgwODUxOTgsImlkIjoiN2Y1ZGM3M2UtZTA5Ny00ZThlLWJhN2MtNWVkODI4ZmFiYzc0In0.-Kb8MhiC81AdF9BIqj4D8x-NN9JM57d9SVFr9fK0sKQ

{
  "name": "Test update manual rute",
  "phone":"Desc manual rute update"
}